spring:
  application:
    name: springBoot
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    initialization-mode: always
    continue-on-error: false
  h2:
    console:
      enabled: true
      path: /h2
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: test
  application:
    name: springBoot
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    initialization-mode: always
    continue-on-error: false
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: NONE